# -*- coding: utf-8 -*-
#
# landingpage documentation build configuration file, created by
# sphinx-quickstart on Mon Mar  6 09:17:01 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
import sys, os
import sphinx_bootstrap_theme
#import recommonmark.parser (insertion documents avec syntaxe Markdown)
from recommonmark.parser import CommonMarkParser
from recommonmark.transform import AutoStructify

# include at end of every file
rst_epilog = """
.. substitutions
.. |OTU| replace:: Olivier TURLIER
.. |MAR| replace:: Marc O

.. |knp| replace:: **Canopee**

.. |acad| replace:: **AutoCAD**
.. |rhin| replace:: **Rhino 3D**
.. |grasp| replace:: **Grasshopper**
.. |su| replace:: **Sketchup**
.. |rvt| replace:: **Revit**
.. |dyn| replace:: **Dynamo**

.. |BDX| replace:: Bordeaux
.. |TLS| replace:: Toulouse
.. |MPL| replace:: Montpellier
.. |MRS| replace:: Marseille
.. |NCE| replace:: Nice

.. |rst| replace:: **reStructuredText**
.. |site| replace:: site Internet

.. |cms| replace:: :abbr:`CMS (Content Management System)`
.. |dita-ot| replace:: :abbr:`DITA-OT (DITA Open Toolkit)`
.. |github| replace:: *GitHub*
.. |git| replace:: *Git*
.. |gui| replace:: :abbr:`GUI (Graphical User Interface)`
.. |ide| replace:: :abbr:`IDE (Integrated Development Environment)`
.. |latex| replace:: *LaTeX*
.. |sphinx| replace:: Python Sphinx
.. |ssh| replace:: :abbr:`SSH (Secure Shell)`

.. links
.. _Linkedin: http://www.linkedin.com
.. _Autodesk: http://www.autodesk.fr/
"""

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.intersphinx',
    'sphinx.ext.mathjax',
    'sphinx.ext.githubpages',
    'sphinxcontrib.email',
    # 'sphinxcontrib.exceltable', # no compile, sphinx ask too much ...
    'sphinxcontrib.googlemaps',
    'sphinxcontrib.youtube'
]

# sphinxcontrib.googlemaps
# googlemaps_domain
#     Default value is ``http://maps.google.co.jp``.
#     The property defines the full domain, including protocol, to use for Google Map iFrame.
# googlemaps_language
#     Default value is ``ja`` for japanese.
#     The property defines the language parameter to include in domain.
#
# sphinxcontrib.youtube
# googlemaps_width
#     Default value is ``600``.
#     The property defines the width of iFrame.
# googlemaps_height
#     Default value is ``350``.
#     The property defines the height of iFrame.

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
#source_suffix = '.rst'
#Markdown support
source_parsers = {
    '.md': 'recommonmark.parser.CommonMarkParser',
}
source_suffix = ['.rst', '.md']


# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'CANOPEE'
copyright = u'2001-2017, Olivier TURLIER'
author = u'Olivier TURLIER'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
#version = u'1.'
# The full version, including alpha/beta/rc tags.
release = u'1.0.1'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'fr'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# today = ''
#
# Else, today_fmt is used as the format for a strftime call.
#
today_fmt = '%d-%m-%Y'

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}
#this is the  sphinx_bootstrap_theme
html_theme = 'bootstrap'
html_theme_path = sphinx_bootstrap_theme.get_html_theme_path()

html_theme_options = {
    'bootswatch_theme': "readable",
#redadble and united seem good
# Options are nothing (default) or the name of a valid theme such
# as "amelia" or "cosmo".
#
# Example themes:
# * flatly
# * sandstone (v3 only)
# * united
# * yeti (v3 only)
#see http://bootswatch.com/ for a list
# Render the next and previous page links in navbar. (Default: true)
    'navbar_sidebarrel': False,
# Render the current pages TOC in the navbar. (Default: true)
    'navbar_pagenav': False,
    'navbar_fixed_top': "true",
    'globaltoc_depth': 0,
#    'globaltoc_includehidden': False,
#this leaves the website global menu, untranslated, without name (only an arrow)
    'navbar_site_name': "", #CANOPEE
#menus in a row, topbar (it works, but is untranslatable)
#better solution in layout.html
    'navbar_links': [('Formations', 'cours'), ('Documentation', 'docs'), ('Assistance', 'assist'), ('Equipe', 'team')],

    # Choose Bootstrap version.
    # Values: "3" (default) or "2" (in quotes)
    'bootstrap_version': "3"
}

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None
html_title = "Canopee - Formations DAO"

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None
html_short_title = "Canopee"

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None
#html_logo = 'images/canopee_logo.png'

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None
html_favicon = 'images/canopee_ico.ico'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
# html_extra_path = ["_static/404.html"]
html_extra_path = ['_static/extra/']

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}
#
## permet d'afficher contenu local de "cours.rst" dans la "sidebar", utile pour les grandes pages
# le nom 'cours' doit correspondre à un fichier, ici "cours.rst"
#html_sidebars = {'cours': ['localtoc.html', 'searchbox.html']}
html_sidebars = {'cours': ['localtoc.html'], 'docs': ['localtoc.html'], 'assist': ['localtoc.html'],}


# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True
html_show_sourcelink = False

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True

# Remove permalinks "P" at ends of each title
#
html_add_permalinks = False

# If false, no index is generated.
#
html_use_index = False

# If true, links to the reST sources are added to the pages.
#
html_show_sourcelink = False

# Remove copying of source
#
html_copy_source = False

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr', 'zh'
#
html_search_language = 'fr'

#
# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
html_use_smartypants = True



# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'index'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'landingpage.tex', u'landingpage Documentation',
     u'Olivier TURLIER', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'landingpage', u'landingpage Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'landingpage', u'landingpage Documentation',
     author, 'landingpage', 'One line description of project.',
     'Miscellaneous'),
]




# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'https://docs.python.org/': None}
